### ISSUE TITLE
Broken background rendering in notebook 7

### ISSUE THREAD

**Issue by psychemedia** [innovationOUtside/jupyterlab_empinken_extension#5]
In notebook 7, if a markdown cell is selected, then an empinkened background is not displayed.

Need to add another rule with increased specificity, eg:

```css
body[data-notebook='notebooks'] .jp-Notebook .jp-Cell.jp-MarkdownCell.jp-Notebook-cell.jp-mod-active.iou-activity-node {
    background-color: var(--iou-activity-bg-color) !important;
}
```

It would be better if we could simplify this rule but still have priority the rule(s) that appears to trump it:

```css
body[data-notebook='notebooks'] .jp-Notebook.jp-mod-commandMode .jp-Cell.jp-mod-active.jp-mod-selected:not(.jp-mod-multiSelected) {
    background: var(--jp-layout-color0) !important;
}
```
